# Generated by Django 4.2.1 on 2023-05-24 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.SmallIntegerField()),
                ('website', models.CharField(max_length=300)),
                ('promoCodes', models.CharField(max_length=300)),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popupTitle', models.CharField(max_length=200)),
                ('popupContent', models.CharField(max_length=200)),
                ('popupId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='popup', to='myapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='ChatGPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitorInputChatGPT', models.TextField(max_length=2000)),
                ('visitorOutputChatGPT', models.TextField(max_length=5000)),
                ('clientInputChatGPT', models.TextField(max_length=5000)),
                ('processedTitle', models.TextField(max_length=5000)),
                ('processedContent', models.TextField(max_length=5000)),
                ('requestId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chatgpt', to='myapp.popup')),
            ],
        ),
    ]
