# Generated by Django 4.2.1 on 2023-05-24 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_client_popup_chatgpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='promoCodes',
        ),
        migrations.AlterField(
            model_name='chatgpt',
            name='requestId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatgpt', to='myapp.popup'),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popupId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popup', to='myapp.client'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='myapp.client')),
            ],
        ),
    ]
