# Generated by Django 4.2.1 on 2023-05-24 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_client_promocodes_alter_chatgpt_requestid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgpt',
            old_name='visitorInputChatGPT',
            new_name='inputChatGPT',
        ),
        migrations.RenameField(
            model_name='chatgpt',
            old_name='processedContent',
            new_name='outputChatGPT',
        ),
        migrations.RemoveField(
            model_name='chatgpt',
            name='clientInputChatGPT',
        ),
        migrations.RemoveField(
            model_name='chatgpt',
            name='processedTitle',
        ),
        migrations.RemoveField(
            model_name='chatgpt',
            name='visitorOutputChatGPT',
        ),
        migrations.AddField(
            model_name='client',
            name='aboutClient',
            field=models.TextField(default=django.utils.timezone.now, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='clientHasProducts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='clientHasPromotions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='helpPage',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='website',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='code',
            name='code_answer',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='code',
            name='question',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoCodes', to='myapp.client'),
        ),
        migrations.CreateModel(
            name='PopupEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PopupEngagementStart', models.DateTimeField(default=django.utils.timezone.now)),
                ('PopupEngagementEnd', models.DateTimeField()),
                ('PopupEngagementId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='myapp.popup')),
            ],
        ),
        migrations.CreateModel(
            name='ClientProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productPrice', models.SmallIntegerField()),
                ('productLink', models.CharField(max_length=300)),
                ('productDetails', models.TextField(max_length=3000)),
                ('productPriceWithPromo', models.CharField(max_length=300)),
                ('clientProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientProducts', to='myapp.client')),
            ],
        ),
        migrations.AlterField(
            model_name='chatgpt',
            name='requestId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatgpt', to='myapp.popupengagement'),
        ),
    ]
