# Generated by Django 4.2.1 on 2023-05-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_visitorinputchatgpt_chatgpt_inputchatgpt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popupengagement',
            old_name='PopupEngagementEnd',
            new_name='popupEngagementEnd',
        ),
        migrations.RenameField(
            model_name='popupengagement',
            old_name='PopupEngagementId',
            new_name='popupEngagementId',
        ),
        migrations.RenameField(
            model_name='popupengagement',
            old_name='PopupEngagementStart',
            new_name='popupEngagementStart',
        ),
    ]
