# Generated by Django 4.2.1 on 2023-05-24 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_popupengagementend_popupengagement_popupengagementend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupengagement',
            name='popupEngagementId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popupEngagement', to='myapp.popup'),
        ),
    ]
