# Generated by Django 4.2.1 on 2023-05-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_chatgpt_requestid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgpt',
            name='requestId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chatgpt', to='myapp.popupengagement'),
        ),
    ]
