# Generated by Django 4.2.1 on 2023-05-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_chatgpt_outputchatgpt_alter_client_aboutclient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgpt',
            name='requestId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatgpt', to='myapp.popupengagement'),
        ),
        migrations.AlterField(
            model_name='popupengagement',
            name='popupEngagementId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popupEngagement', to='myapp.popup'),
        ),
    ]
