# Generated by Django 4.2.1 on 2023-05-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_chatgpt_requestid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupengagement',
            name='popupEngagementUniqueIdentifier',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
