# Generated by Django 4.2.1 on 2023-05-29 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_popupengagement_popupengagementuniqueidentifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popupBackgroundColor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupBorderColor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupBorderPadding',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupCTAButtonBorderColor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupCTAButtonHasBorder',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupCTAButtonHeight',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupCTAButtonLink',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupCTAButtonPositioning',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupCTAButtonText',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupCTAButtonTextColor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupCTAButtonWidth',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupCloseButtonPositioning',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupCloseButtonText',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupCloseButtonTextColor',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupCloseButtonTextSize',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupContentHasBorder',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupContentHeight',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupContentPositioning',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupContentTextColor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupContentWidth',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupEmailSubscription',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupGoal',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupHeight',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupImage',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupPromo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupTitleHeight',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupTitlePositioning',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupTitleTextColor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupTitleWidth',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupWidth',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='PopupAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popupAdditionalText', models.CharField(max_length=200, null=True)),
                ('popupAdditionalLink', models.CharField(max_length=50, null=True)),
                ('popupAdditionalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popupAdditional', to='myapp.popup')),
            ],
        ),
    ]
