# Generated by Django 4.2.1 on 2023-05-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_popup_popupbackgroundcolor_popup_popupbordercolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='popupCloseButtonTextColor',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
