# Generated by Django 4.2.1 on 2023-05-31 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_popup_popupclosebuttontextcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popupChatButtonBoxColor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupChatButtonFocusBorderColor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupChatButtonPositioning',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupChatButtonText',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupChatButtonTextColor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupChatButtonTextSize',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupChatHistoryBoxColor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupChatHistoryFocusBorderColor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupChatHistoryPositioning',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupChatHistoryText',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupChatHistoryTextColor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupChatHistoryTextSize',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupSuggestionButtonBoxColor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupSuggestionButtonFocusBorderColor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupSuggestionButtonPositioning',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupSuggestionButtonText',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupSuggestionButtonTextColor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupSuggestionButtonTextSize',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popupengagement',
            name='conversationStartedAtWebsiteLink',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PopupChatSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popupSuggestion', models.TextField(max_length=50, null=True)),
                ('popupChatSuggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popupChatSuggestion', to='myapp.popup')),
            ],
        ),
    ]
