# Generated by Django 4.2.1 on 2023-05-31 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_popup_popupchatbuttonboxcolor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popup',
            name='popupChatHistoryText',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='popupSuggestionButtonText',
        ),
    ]
