# Generated by Django 4.2.1 on 2023-06-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_popup_popupchathistorytext_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popup',
            name='popupBorderPadding',
        ),
        migrations.AddField(
            model_name='popup',
            name='popupBorderWidth',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
