# Generated by Django 4.2.1 on 2023-06-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_popupchathistoryboxcolor_popup_popupchathistoryinputboxcolor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popup',
            old_name='popupChatHistoryTextSize',
            new_name='popupChatHistoryInputTextSize',
        ),
        migrations.AddField(
            model_name='popup',
            name='popupChatHistoryOutputTextSize',
            field=models.SmallIntegerField(null=True),
        ),
    ]
