# Generated by Django 4.2.1 on 2023-06-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_popupchathistorytextsize_popup_popupchathistoryinputtextsize_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popup',
            old_name='popupChatHistoryTextColor',
            new_name='popupChatHistoryInputTextColor',
        ),
        migrations.RenameField(
            model_name='popup',
            old_name='popupChatHistoryInputTextSize',
            new_name='popupChatHistoryTextSize',
        ),
        migrations.RemoveField(
            model_name='popup',
            name='popupChatHistoryOutputTextSize',
        ),
        migrations.AddField(
            model_name='popup',
            name='popupChatHistoryOutputTextColor',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
