# Generated by Django 4.2.1 on 2023-06-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_popupchathistorytextcolor_popup_popupchathistoryinputtextcolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='popupImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
