# Generated by Django 4.2.1 on 2023-06-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_popup_popupimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popupImageHeight',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupImageWidth',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
