# Generated by Django 4.2.1 on 2023-06-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_popup_popupimagebordercolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popupTextMarginLeft',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupTextMarginRight',
            field=models.SmallIntegerField(null=True),
        ),
    ]
