# Generated by Django 4.2.1 on 2023-06-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_popup_popuptextmarginleft_popup_popuptextmarginright'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popupCloseButtonBoxColor',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
