# Generated by Django 4.2.1 on 2023-06-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_popup_popupclosebuttonboxcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='popupCloseButtonTextSize',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
