# Generated by Django 4.2.1 on 2023-06-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_popup_popupclosebuttontextsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popupCloseButtonVariant',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
