# Generated by Django 4.2.1 on 2023-06-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_popup_popupclosebuttonvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popupCloseButtonColorScheme',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
