# Generated by Django 4.2.1 on 2023-06-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_popup_popupclosebuttoncolorscheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popupCTAPercentage',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupChatHistoryPercentage',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupChatSendPercentage',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupTitleAndContentPercentage',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
