# Generated by Django 4.2.1 on 2023-06-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_popup_popupctapercentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='popupCTAPercentage',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popupChatHistoryPercentage',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popupChatSendPercentage',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popupTitleAndContentPercentage',
            field=models.SmallIntegerField(null=True),
        ),
    ]
