# Generated by Django 4.2.1 on 2023-06-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_popup_popupctapercentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='popupCTAPercentage',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popupChatHistoryPercentage',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popupChatSendPercentage',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popupTitleAndContentPercentage',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
