# Generated by Django 4.2.1 on 2023-06-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_popup_popupctapercentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popupSendButtonColor',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupSendButtonText',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupSendButtonTextColor',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupSendButtonVariant',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
