# Generated by Django 4.2.1 on 2023-06-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_popup_popupsendbuttoncolor_popup_popupsendbuttontext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popupSendButtonScheme',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
