# Generated by Django 4.2.1 on 2023-06-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_popup_popupsendbuttonscheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popupExampleInputChatGPT',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupExampleOutputChatGPT',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
