# Generated by Django 4.2.1 on 2023-06-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_popup_popupexampleinputchatgpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgpt',
            name='chatWebsiteURL',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
