# Generated by Django 4.2.1 on 2023-06-29 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_popupfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupfiles',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client'),
        ),
    ]
