# Generated by Django 4.2.1 on 2023-07-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_alter_popupfiles_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popupBorderBoxShadow',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupBorderRadius',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupChatHistoryFontSize',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupContentFontSize',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupContentFontWeight',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupTitleFontSize',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupTitleFontWeight',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popupCloseButtonBoxColor',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popupCloseButtonTextColor',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popupContentTextColor',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popupImageBorderColor',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popupTitleTextColor',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
