# Generated by Django 4.2.1 on 2023-07-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_popup_popupborderboxshadow_popup_popupborderradius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popupHasLogo',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='popupLogo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
