# Generated by Django 4.2.1 on 2023-07-01 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_popup_popuphaslogo_popup_popuplogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInformationForChatGPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatProblemIsYourCompanySolving', models.TextField(max_length=400, null=True)),
                ('whatServicesDoYouOffer', models.TextField(max_length=400, null=True)),
                ('howCanCustomersReachYouOrYourTeam', models.TextField(max_length=400, null=True)),
                ('whatAreFAQs', models.TextField(max_length=2000, null=True)),
                ('anyOtherInformation', models.TextField(max_length=2000, null=True)),
                ('howMuchDiscountCanYouDoMaximum', models.TextField(max_length=2000, null=True)),
                ('doYouWantYourOwnPopupTitleAndContent', models.BooleanField(default=True)),
                ('whatIsYourMostSoldProduct', models.BooleanField(max_length=2000, null=True)),
                ('chatGPTInformationKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informationForChatGPT', to='myapp.popup')),
            ],
        ),
        migrations.CreateModel(
            name='PopupProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productPrice', models.IntegerField(null=True)),
                ('productIsDiscountable', models.BooleanField(default=False)),
                ('productPriceAfterDiscount', models.CharField(max_length=300, null=True)),
                ('productPromo', models.CharField(max_length=300, null=True)),
                ('productLink', models.CharField(max_length=200, null=True)),
                ('productSpecs', models.TextField(max_length=3000, null=True)),
                ('productImage', models.ImageField(null=True, upload_to='')),
                ('productSpecificChatGPTInformationKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productSpecificInformationForChatGPT', to='myapp.popup')),
            ],
        ),
        migrations.AlterField(
            model_name='popupengagement',
            name='conversationStartedAtWebsiteLink',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='ClientProducts',
        ),
    ]
