# Generated by Django 4.2.1 on 2023-07-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_generalinformationforchatgpt_popupproducts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupproducts',
            name='productPriceAfterDiscount',
            field=models.IntegerField(null=True),
        ),
    ]
