# Generated by Django 4.2.1 on 2023-07-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_alter_popupproducts_productpriceafterdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupproducts',
            name='productCurrency',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
