# Generated by Django 4.2.1 on 2023-07-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_rename_productpromo_popupproducts_productpromocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformationforchatgpt',
            name='whatIsYourMostSoldProduct',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
