# Generated by Django 4.2.1 on 2023-07-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_alter_generalinformationforchatgpt_whatisyourmostsoldproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgpt',
            name='chatWebsiteURL',
        ),
    ]
